version: "3.8"
services:
  web:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_app
  tests:
    build: .
    command: npm test
    depends_on:
      - db